### ISSUE TITLE
Player gets randomly stuck on terrain

### ISSUE THREAD

**Issue by IG88Droid** [FIS-game-development-club/2019#4]
When running left and right on the test scene, the player will randomly stop moving and be unable to move past a certain point in one direction, ostensibly because the player is stuck on the terrain.

**Comment by Frederik-Hollis** [comment]
sometimes moving around a bit solves the problem

**Comment by Frederik-Hollis** [comment]
really?

**Comment by karsten2004** [comment]
yes

**Comment by karsten2004** [comment]
it is fixed
